## Numpy - Numerical Python - python library for numerical calculation 

### Lets see what we gonna learn:
  - Numpy Introduction 
  - Numpy Environment
  - Numpy ndarray object 
  - Numpy data types
    - data type objects (dtype)
  - Numpy Array attributes
    - np.shape
    - np.ndim
    - np.itemsize
    - np.flags
  - array creation routines
    - np.empty
    - np.zeros
    - np.ones
  - array from existing data
    - np.asarray
    - np.frombuffer
    - np.fromiter
  - array from numerical ranges
    - np.arange
    - np.linspace
    - np.logspace
  - Numpy indexing and slicing
  - Numpy advanced Indexing
    - Integer Indexing
    - Boolean array indexing
  - Numpy Broadcasting
  - Numpy : Iterating over array
    - Iteration order
    - Modifying array values
    - External Loop
    - Broadcasting Iteration
  - Numpy array Manipulation
  - Numpy Binary Operator
  - Numpy String function 
  - Numpy Mathematical Function
  - Numpy Arithmetic Operation
  - Numpy Statistical Function
  - Numpy sort, search and counting function 
  - Numpy Byte Swapping
  - Numpy copies and views
  - Numpy Matrix Library
  - Numpy Linear Algebra
  - Numpy Matplotlib
  - Numpy Histogram using Matplotlib
  - Numpy I/O 

## Numpy Introduction: 

### About Numpy:
- It is a **library** consisting of **multidimensional array objects** and a collection of routines for processing of array.It is open source, which is an added advantage of NumPy.
### Operations using NumPy 
Using NumPy, a developer can perform the following operations: 
- **Mathematical and logical operations** on arrays.  
- **Fourier transforms and routines** for shape manipulation.  
- **Operations related to linear algebra**. **NumPy has in-built functions for linear algebra and random number generation.** 

### NumPy – A Replacement for MatLab 
NumPy is often used along with packages like **SciPy (Scientific Python)** and **Mat−plotlib (plotting library).**
This combination is widely used as a replacement for MatLab, a popular platform for technical computing.


## Numpy Environment 
Standard  Python  distribution  doesn't  come  bundled  with  NumPy  module.  A  lightweight alternative is to install NumPy using popular Python package installer, pip. ```pip install numpy```.The  best  way  to  enable  NumPy  is  to  use  an  installable  binary  package  specific  to  your operating  system.  These  binaries  contain  full  SciPy  stack  (inclusive  of  NumPy,  SciPy, matplotlib, IPython, SymPy and nose packages along with core Python). 

- Test the numpy package installed into the OS. JUST ```import numpy``` if this statement into the py file throw any error. Install it using ```pip install numpy```. Otherwise it means that installed into OS. We can use the power of NumPy then. 

- In general and common convention that the numpy package imported and alias as np ```import numpy as np```.
- To follow the numpy [documentation](https://numpy.org/doc/2.2/)
- To follow the [start_up guide](https://numpy.org/doc/2.2/user/absolute_beginners.html)
- To follow the in depth user guide with background operations - [user_guide](https://numpy.org/doc/2.2/user/index.html#user)
- To folLow the [Numpy API](https://numpy.org/doc/2.2/reference/index.html#reference)  

## Numpy - ndarray Object:

In NumPy, the core data structure is called an "ndarray" which is essentially a multi-dimensional array where all elements are of the same type (like numbers). Imagine a grid where you can access any element using its position (index) starting from 0, and every element takes up the same amount of space in memory.

#### Key points about ndarray:
**N-dimensional:**
It can hold data in multiple dimensions, like a 2D table (rows and columns) or a 3D cube.

**Homogeneous:**
All elements within an ndarray must be of the same data type (like integers, floats, etc.).

**Zero-based indexing:**
To access an element, you count from 0, so the first element is at index 0.

**Data type object (dtype):**
Each ndarray has a "dtype" which specifies the exact type of data it holds (e.g., int32 for 32-bit integers).

>> Think of it like this:

**ndarray is like a box:** It holds all your data organized in a specific structure.

**dtype is like a label on the box:** It tells you what type of items are inside (e.g., "integer", "float").

**Accessing elements is like picking items from the box:** You use their position (index) to get the specific value.

An instance of an ndarray class can be constructed by different array creation routines described later. But now the common and basic way creating ndarray using the array function in the numpy.It creates an ndarray from any object exposing array interface, or from any method that 
returns an array. 
```py
  numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
  numpy.array([1,2,3,4,5])
  numpy.array((1,2,3,4,5,6))
```
**object** -> any object exposing array interface method return the array or any nested sequence
**dtype** -> any desired data type of array "float" or "int"
**copy** -> optional by default (True)
order -> C(row-major memory layout) or F(column major memory layout) or K 
subok -> inDefault set to False
**ndmin** -> ensures atleast n dimension in integer it may be 1,2,3,4,5 any



In [70]:
# numpy_learning
# to install numpy > pip install numpy and then import the module into the python file.
# Package Importing and alias as np
import numpy as np

array_by_list = np.array([1,2,3,4])
array_by_tuple = np.array((7,8,9,0))

print(array_by_list)
print(array_by_tuple)
print(type(array_by_list))
print(type(array_by_tuple))

# 0 - dimensional array means the scalar value
zerod_array = np.array(20) # scalar value and its type numpy.ndarray
print(zerod_array) # scalar value

# 1-D array
oned_array = np.array([4,9,7,5,8])
print("oned_array :", oned_array)

#2D array 
twod_array = np.array([[1,1,1,0,1],[1,5,6,8,0],[3,5,3,5,7]]) # 2d 3x5 matrix 
print("twod_array :", twod_array) 
print("twod_array_shape :", twod_array.shape) # show row x column
print("twod_array_itemsize :", twod_array.itemsize) 
print("twod_array_ndim :", twod_array.ndim)

#3D Array 
threed_array = np.array([[[1,2,3],[1,0,9]],[[1,2,5],[2,5,6]]])
print("threed_array:", threed_array)
print("threed_array_shape:", threed_array.shape)
print("threed_array_ndim:", threed_array.ndim)


# complex matrix
complex_array = np.array([1,2,3,1j], dtype="complex")
print("complex_array: ",complex_array)

# create the array with a arange function 
range_arr = np.arange(1,26) 
print(range_arr)
print(range_arr.shape)
print(range_arr.ndim)


[1 2 3 4]
[7 8 9 0]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
20
oned_array : [4 9 7 5 8]
twod_array : [[1 1 1 0 1]
 [1 5 6 8 0]
 [3 5 3 5 7]]
twod_array_shape : (3, 5)
twod_array_itemsize : 8
twod_array_ndim : 2
threed_array: [[[1 2 3]
  [1 0 9]]

 [[1 2 5]
  [2 5 6]]]
threed_array_shape: (2, 2, 3)
threed_array_ndim: 3
complex_array:  [1.+0.j 2.+0.j 3.+0.j 0.+1.j]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
(25,)
1


### Numpy Data types 
- NumPy supports a much greater variety of numerical types than Python does.  
- The following table shows different scalar data types defined in NumPy.
  - **bool_** Boolean (True or False) stored as a byte 
  - **int_** Default integer type (same as C long; normally either int64 or int32) 
  - **intc** Identical to C int (normally int32 or int64) 
  - **intp** Integer used for indexing (same as C ssize_t; normally either int32 or int64) 
  - **int8** Byte (-128 to 127) 
  - **int16** Integer (-32768 to 32767) 
  - **int32** Integer (-2147483648 to 2147483647) 
  - **int64** Integer (-9223372036854775808 to 9223372036854775807) 
  - **uint8** Unsigned integer (0 to 255) 
  - **uint16** Unsigned integer (0 to 65535) 
  - **uint32** Unsigned integer (0 to 4294967295) 
  - **uint64** Unsigned integer (0 to 18446744073709551615) 
  - **float_** Shorthand for float64 
  - **float16** Half precision float: sign bit, 5 bits exponent, 10 bits mantissa 
  - **float32** Single precision float: sign bit, 8 bits exponent, 23 bits mantissa 
  - **float64** Double precision float: sign bit, 11 bits exponent, 52 bits mantissa 
  - **complex_** Shorthand for complex128 
  - **complex64** Complex number, represented by two 32-bit floats (real and imaginary components) 
  - **complex128** Complex number, represented by two 64-bit floats (real and imaginary components)

- Each built-in data type has a character code that uniquely identifies it. 
  - 'b': boolean 
  - 'i': (signed) integer 
  - 'u': unsigned integer 
  - 'f': floating-point 
  - 'c': complex-floating point 
  - 'm': timedelta 
  - 'M': datetime 
  - 'O': (Python) objects 
  - 'S', 'a': (byte-)string 
  - 'U': Unicode 
  - 'V': raw data (void) 
 
  


In [116]:
# Numpy Data type 
dt = np.dtype(np.int64)
print(dt)
dt = np.dtype("i4")
print(dt)

# Way 1 
datatype = np.dtype([("age" , np.int64)])
arr = np.array([(10,),(20,),(30,)], dtype = datatype)
print(arr["age"])

# Shortest way 
array = np.array([10,20,30], dtype=np.int64)
print(array)

# The following examples define a  structured data type called  student  with a string field 'name', 
# an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.

student = np.dtype([("name", "S20"),("age" , "i1"),("marks", "float")])
print(student)

a = np.array([("natraj", 25, 75.45),("kari",22, 74.1)], dtype=student)
print(a)


# students = np.dtype([("name", "S20"),("age","int"),("marks", "float")])
# student_table = np.array([("Natraj" , 25 , 77), ("Karikalan", 22, 70), ("Athista", 20 , 99)], dtype=students)
# print(student_table)

int64
int32
[10 20 30]
[10 20 30]
[('name', 'S20'), ('age', 'i1'), ('marks', '<f8')]
[(b'natraj', 25, 75.45) (b'kari', 22, 74.1 )]


Numpy Attributes: 
ndarray.shape -> returns a tuple consisting of array dimensions.It can also be used to resize the array. 
ndarray.ndim -> This array attribute returns the number of array dimensions.
ndarray.reshape(<block> <row_number> <column_number>) -> we can reshape the array by this method
np.arange(int) -> return the 1d array with range of value we mentioned
array.itemsize -> This array attribute returns the length of each element of array in bytes.
numpy.flags -> The ndarray object has the following attributes. Its current values are returned by this function.

In [126]:
# ndarray.shape
# ndarray.ndim 
# ndarray.size

# 2d example
arr = np.array([[1,2,3,4],[5,6,7,8],[4,3,2,1]])
print(arr)
print(arr.shape) # returns the tuple (row_count , column_count)
print(arr.ndim)
arr.shape = (6,2) # reassigning to change the shape. 
print(arr)
arr.reshape(4,3)
print(arr)
print(arr.ndim) 
print("itemsize: ", arr.itemsize)


# 3d 
arr = np.array([[[1,2,3,4],[5,6,7,8],[4,3,2,1]],[[6,3,8,2],[1,5,0,4],[1,4,7,0]]])
print(arr) 
print(arr.shape) # returns the tuple (block count ,row_count , column_count)
print(arr.ndim)
arr.shape = (2,4,3) # reassigning to change the shape. 
print(arr) 
#  we can reshape it using the function 
arr.reshape(2,2,6)
print(arr)
print("Size :" , arr.size) 

# "itemsize" array attribute returns the length of each element of array in bytes.
arr = np.array([1,2,3,4,5], dtype="float")
print(arr)
print("itemsize:", arr.itemsize)
print("flags: ", arr.flags)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]
(3, 4)
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [4 3]
 [2 1]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [4 3]
 [2 1]]
2
itemsize:  8
[[[1 2 3 4]
  [5 6 7 8]
  [4 3 2 1]]

 [[6 3 8 2]
  [1 5 0 4]
  [1 4 7 0]]]
(2, 3, 4)
3
[[[1 2 3]
  [4 5 6]
  [7 8 4]
  [3 2 1]]

 [[6 3 8]
  [2 1 5]
  [0 4 1]
  [4 7 0]]]
[[[1 2 3]
  [4 5 6]
  [7 8 4]
  [3 2 1]]

 [[6 3 8]
  [2 1 5]
  [0 4 1]
  [4 7 0]]]
Size : 24
[1. 2. 3. 4. 5.]
itemsize: 8
flags:    C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Numpy Array creation routines: 
A new ndarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.

- numpy.empty(shape, dtype="float" , order="C") shape of an empty array in int or tuple of int
  - The shape can be mean in an array or tuple form [2,3] or (2,3) or [2,3,4] or (2,3,3)
  - it expect shape only, the dtype and order set to float and C respectively. 
  - The elements in an array show random values as they are not initialized. 
- numpy.zeros(shape, dtype="float", order="C") 
- numpy.ones(shape, dtype="int")

In [ ]:
empty_array = np.empty([2,3], dtype="int")
print("emprty_array:" , empty_array)

zeros_array = np.zeros([2,3,3], dtype="i1", order="C")
print("zeros_array:", zeros_array)
zeros_1d = np.zeros([1,5])
print("zeros_1d:" , zeros_1d) # in default the data type is float 

zeros_2d = np.zeros((2,4), dtype="i2")
print("zeros_2d:", zeros_2d) 

array_of_5_zeros = np.zeros(5)
print("array_of_5_zeros: ", array_of_5_zeros)


ones_array = np.ones(5) 
print("ones_array:", ones_array)

ones_int_array = np.ones(5, dtype="int") 
print("ones_array:", ones_int_array)

ones_2d = np.ones((2,2), dtype="int")
print(ones_2d)

### Numpy - Array from existing data

How to create an array from existing data?
lets imagine we have a matrix in some shape and dtype and order, what if we want to make an new array as like the same we have already with some changes in ahape and dtype and order. here, we are gonna use 
>> np.asarray(shape, dtype="None", order="None")

In [125]:
# we have a input data: 
a = np.array([[1,2,3,4],[2,2,3,4]])
print(a)

#  here we use the array "a" as a input for the creation of new_array. 
# if we dont set any dtype or order in the asarray(), it retains the input array dtype and orders.
new_array = np.asarray(a, dtype="int", order="C")
print(new_array)

new_list= [1,2,3,4,5,6]
new_tuple = (9,8,7,6,6,5,5)

li_array = np.asarray(new_list)
tu_array = np.asarray(new_tuple , dtype="float")

print(li_array)
print(tu_array)

# binary forma of string can be converted to array of letters
# numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)

# we can create the array from the iter() along with dtype
new_range = range(10)
print(new_range)
iterator = iter(new_range)

new_arr = np.fromiter(iterator, dtype="int")
print(new_arr)



[[1 2 3 4]
 [2 2 3 4]]
[[1 2 3 4]
 [2 2 3 4]]
[1 2 3 4 5 6]
[9. 8. 7. 6. 6. 5. 5.]
range(0, 10)
[0 1 2 3 4 5 6 7 8 9]
