# **NumPy**

In [5]:
!pip install numpy  # Installing of the Module

In [22]:
import numpy  as np  # importing of the Module --- this is Mandatory

In [23]:
array1 = np.array(45)  # 0-Dimensional Array ---- the result will be scalar value (SINGLE VALUE)
print(array1)
print(array1.ndim)

45
0


In [24]:
array2 = np.array([1,2,3,4,5,6])
print(array2)
print(array2.ndim)

[1 2 3 4 5 6]
1


In [29]:
array3 = np.array([[1,2,3,],
 [4,5,6,]])
print(array3)
print(array3.ndim)

[[1 2 3]
 [4 5 6]]
2


In [30]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [31]:
array2 = np.array([1,2,3,4,5])
print(array2)
print(array2.ndim)

[1 2 3 4 5]
1


In [40]:
array4 = np.array([[[[1,2,3], [4,5,6],
                   [7,8,9],[10,11,12],
                   [13,14,15], [16,17,18]]]])
print(array4)
print(array4.ndim)
print(array4.shape)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]
   [13 14 15]
   [16 17 18]]]]
4
(1, 1, 6, 3)


In [39]:
array5 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9], [10,11,12]]])
print(array5)
print(array5.ndim)

print(array5.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [ ]:
'''
0D
1D
2D
3D
Print the array
print the ndim
print the shape

'''


In [45]:
array5=np.array([[[1,2,3],[4,5,6],[5,6,7]]])
print(array5)
print(array5.ndim)
print(array5.shape)


[[[1 2 3]
  [4 5 6]
  [5 6 7]]]
3
(1, 3, 3)


In [46]:
array1 = np.array([[1, 2],[2, 4]])
print(array1)
print(array1.ndim)

[[1 2]
 [2 4]]
2


In [47]:
# Arthimetic Operators
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [49]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [2,3,4,6]
print(a+b+c)

[1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 6]


In [50]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
# I want to find the sum of the elements?
print(a.sum())

55


In [51]:
# I want to find min value in the array?
print(a.min())

1


In [52]:
# I want to find the max value in the array?
print(a.max())

10


In [53]:
# I  want to find the average value in the array?
print(a.mean())

5.5


In [54]:
print(a.average())

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [61]:
# my manager asked to generate 3 X 3 matrix with zero's ---- np.zeros
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
print(np.zeros((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [63]:
# my manager asked to generate 3 X 3 matrix with one's ---- np.ones
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [67]:
print(np.ones((3,3,1)))

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


In [68]:
print(np.ones((3,3,10)))

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


In [72]:
print(np.eye((3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
print(np.eye((4)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
print(np.eye((10)))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [75]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [82]:
for i in range(1,11):
  print(i)
  print(type(i))

1
<class 'int'>
2
<class 'int'>
3
<class 'int'>
4
<class 'int'>
5
<class 'int'>
6
<class 'int'>
7
<class 'int'>
8
<class 'int'>
9
<class 'int'>
10
<class 'int'>


In [83]:
print(np.arange(1,11))
print(type(np.arange(1,11)))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [79]:
print(np.arange(1,11,2))   #Odd numbers!!!!

[1 3 5 7 9]


In [80]:
print(np.arange(0,11,2)) # Even Numbers!!!!!

[ 0  2  4  6  8 10]


In [107]:
# Can you generate 4 evenly spaced numbers between 1 and 5
print(np.linspace(0,10,6))

[ 0.  2.  4.  6.  8. 10.]


In [109]:
# Indexing and Slicing
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [110]:
# Slicing
arr = np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [111]:
# I want to print first 3 elements? [10 20 30]
print(arr[0:3])

[10 20 30]


In [112]:
# I want to print [10 30 50]
print(arr[0: :2])

[10 30 50]


In [113]:
array1 = np.array([[1, 2],[2, 4]])
print(array1)
print(array1.ndim)

[[1 2]
 [2 4]]
2


In [114]:
# I want to get the element 4 as an Output:
print(array1[1,1])

4


In [128]:
# Reshaping of the Array
arr = np.array([10,20,30,40,50,60])
print(arr.ndim)

1


In [130]:
# I want to convert the above 1-D array to 2-D Array
print(arr.reshape(2,3))
print(arr.reshape(1,6))
print(arr.reshape(6,1))

[[10 20 30]
 [40 50 60]]
[[10 20 30 40 50 60]]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


In [131]:
arr = np.array([10,20,30,40,50])
print(arr.reshape(1,5))
print(arr.reshape(5,1))

[[10 20 30 40 50]]
[[10]
 [20]
 [30]
 [40]
 [50]]


In [134]:
arr2 = np.array([9,3,5,6,7,7,8,8])
print(arr2.reshape(2,4))
print(arr2.reshape(4,2))
print(arr2.reshape(8,1))
print(arr2.reshape(1,8))

[[9 3 5 6]
 [7 7 8 8]]
[[9 3]
 [5 6]
 [7 7]
 [8 8]]
[[9]
 [3]
 [5]
 [6]
 [7]
 [7]
 [8]
 [8]]
[[9 3 5 6 7 7 8 8]]


In [136]:
# Stacking -
a = np.array([1,2,3,4])  # 4 elements
b = np.array([5,6,7,8]) # 4 elements
c = np.array([23,34,45,56,76,6])  ## 6 elements
print(np.hstack((a,b,c)))

# IN H-Stack -- -Columns will increase

[ 1  2  3  4  5  6  7  8 23 34 45 56 76  6]


In [139]:
d =np.vstack((a,b)) ###  Rows will increase
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [140]:
e =np.vstack((d,c)) ###  Rows will increase
print(e)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 6

In [142]:
a = np.array([12,34,45,56,76,45])
b = np.array([23,45,6,76,78,8])
c = np.array([34,76,23,5,76,7])
print(np.vstack((a,b,c)))

[[12 34 45 56 76 45]
 [23 45  6 76 78  8]
 [34 76 23  5 76  7]]


In [143]:
a = np.array([23,34,56,67,76,78,78])  # is there anyvalue greater than 25?
print(a>25)

[False  True  True  True  True  True  True]


In [145]:
a= np.array([23,34,56,67,76,78,78])  # is there anyvalue greater than 25?
print(a[a>25])

[34 56 67 76 78 78]


In [146]:
a= np.array([23,34,56,67,76,78,78])  # is there anyvalue greater than 25?
print(a[a<50])

[23 34]


In [150]:
a = np.array(["Apple","Apple",56,67,76,78,78,34,5,45,6,])
print(np.diag(a))


[['Apple' '' '' '' '' '' '' '' '' '' '']
 ['' 'Apple' '' '' '' '' '' '' '' '' '']
 ['' '' '56' '' '' '' '' '' '' '' '']
 ['' '' '' '67' '' '' '' '' '' '' '']
 ['' '' '' '' '76' '' '' '' '' '' '']
 ['' '' '' '' '' '78' '' '' '' '' '']
 ['' '' '' '' '' '' '78' '' '' '' '']
 ['' '' '' '' '' '' '' '34' '' '' '']
 ['' '' '' '' '' '' '' '' '5' '' '']
 ['' '' '' '' '' '' '' '' '' '45' '']
 ['' '' '' '' '' '' '' '' '' '' '6']]


In [160]:
print(np.full(5, 5), 2)

[5 5 5 5 5] 2


In [161]:
arr = np.full((3, 4), 99)  # Creates a 3x4 matrix filled with 99
print(arr)

[[99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]]


In [162]:
a = np.full((4,4), 10)
print(a)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
